@startuml

' skinparam linetype ortho


package "Lógica de Negócio de Métricas" {
    component ColetarMetrica.java as coletar_metrica
    component ConsultarMetrica.java as consultar_metrica
    component ConsultarMetricaGithub.java as consultar_metrica_github
    component ConsultarMetricaSonarQube.java as consultar_metrica_sonarqube
    component ColetarMetricaGithub.java as coletar_metrica_github
    component ColetarMetricaSonarQube.java as coletar_metrica_sonarqube
    
    interface IconsultarMetricaGitHub as " "
    interface IconsultarMetricaSonarqube as " "
    interface IcoletarMetricaGitHub as " "
    interface IcoletarMetricaSonarqube as " "
    interface IconsultarMetricas as " "


    IconsultarMetricaGitHub - consultar_metrica_github
    IconsultarMetricaSonarqube - consultar_metrica_sonarqube
    IcoletarMetricaGitHub - coletar_metrica_github
    IcoletarMetricaSonarqube - coletar_metrica_sonarqube

    consultar_metrica - IconsultarMetricas

    consultar_metrica ..> IconsultarMetricaGitHub
    consultar_metrica ..> IconsultarMetricaSonarqube

    coletar_metrica ..> IcoletarMetricaGitHub
    coletar_metrica ..> IcoletarMetricaSonarqube




}

package "Lógica de Negócio de Atividades" {
    component ConsultarAtividade.java as consultar_atividade
    component CriarPeriodoAtividade.java as criar_atividade
    component FinalizarAtividade.java as finalizar_atividade
    component Atividades.java as atividades

    interface Iatividades as " "
    interface IcriarAtividades as " "


    atividades - Iatividades
    criar_atividade - IcriarAtividades

    finalizar_atividade ..> Iatividades
    consultar_atividade ..> Iatividades
    criar_atividade ..> Iatividades

}

package "DatabaseMetricas"{
    database Oracle

    interface Ioracle as " "

    Oracle - Ioracle


}

package "Geração de relatórios" {
    component GerarRelatorio.java as gerar_relatorio

}

package "Configurações de Busca" {
    component ConfigurarParametrosBusca.java as configurar_parametros
    interface IconfigurarParametros as " "
    configurar_parametros - IconfigurarParametros

}

package "Lógica de Negócio de Projetos" {
    component Projetos.java as projetos
    component EscolherProjeto.java as escolher_projeto
    
    interface IescolherProjeto as " "
    interface Iprojetos as " "

    projetos - Iprojetos
    IescolherProjeto - escolher_projeto

    escolher_projeto ..> Iprojetos

    
}


    consultar_metrica_github ..> Ioracle
    consultar_metrica_sonarqube ..> Ioracle
    coletar_metrica_sonarqube ..> Ioracle
    coletar_metrica_github ..> Ioracle

consultar_metrica ..> IconfigurarParametros
coletar_metrica ..> IconfigurarParametros
gerar_relatorio ..> IconsultarMetricas
consultar_atividade ..> IcriarAtividades
criar_atividade ..> IescolherProjeto
projetos ..> Ioracle

@enduml
