@startuml
' Definição dos nós de hardware

' skinparam linetype ortho
left to right direction


node "<<device>> \nServidor Web" as servidor_web {
    component "Interface Web" as Inteface
}

node "<<device>> \nClient Host" as client {
    artifact "Browser" as browser
}

node "<<device>> \nServidor da Aplicação" as aplicacao {
    component "Atividades.Java" as gerir_atividades
    component "Matricas.java" as coletar_metricas
    component "Projetos.java" as projetos
    component "Relatório.java" as relatorio

}

node "<<device>> \nServidor GitHub" as github {
    component "Issues.json" as issue
    component "Commit.json" as commit
    component "PullRequest.json" as pr


}

node "<<device>> \nServidor SonarQube" as sonarqube {
    component "codeacc.json" as coletor_sonarqube
}

node "<<device>> \nServidor Oracle" as oracle {
    database "<<schema>> \nprojetos_metricas" as database
}

' Comunicação entre componentes e nós

servidor_web --- aplicacao : <<http>> 
aplicacao --- oracle : <<jdbc>>
aplicacao --- github: <<http>>
aplicacao --- sonarqube: <<http>>
servidor_web -- client: <<http>>

@enduml
