@startuml
' COLETAR MÉTRICAS DO GITHUB

"usuario : Usuario" as usuario -> ": Sistema" as sistema : solicitarColeta()
activate usuario

sistema -> ": GitHub API" as github : obterMetricas()
activate sistema
activate github

github -> github : verificarDisponibilidade()
activate github
github --> sistema : [disponivel = "sim"] retornarMetricas(dadosMetricas)
deactivate github
deactivate github

sistema -> sistema : processarMetricas(dadosMetricas)
activate sistema

sistema --> usuario : exibirMetricas(dadosMetricas)
deactivate sistema
deactivate sistema

deactivate usuario

sistema -> github : [disponivel = "não"] registrarFalha()
@enduml