@startuml
' GERAR RELATÓRIOS

"usuario : Usuario" as usuario -> ": sistema" as sistema : solicitarGeracaoRelatorio(tipoRelatorio)
activate usuario

sistema -> ": banco de dados" as bd: coletarDadosRelatorio(tipoRelatorio)
activate sistema
activate bd

bd -> bd: buscarDados(tipoRelatorio)
activate bd

bd --> sistema: [dadosEncontrados = "sim"] retornarDados(dadosRelatorio)
deactivate bd

sistema -> sistema: processarDados()
activate sistema

deactivate sistema

sistema -> sistema: formatarRelatorio()
activate sistema

deactivate sistema

sistema --> usuario: exibirRelatorio(relatorio)
deactivate sistema

deactivate usuario

@enduml