@startuml
mainframe COLETAR MÉTRICAS


"usuario : Usuario" as usuario -> "metrica : Metrica" as sistema : solicitaColetaMetricas(inicio, fim)
activate usuario
activate sistema


sistema -// "sonarqube_api : SonarQube" as sonarQube : coletarMetricasSonarQube(inicio, fim)
activate sonarQube

sistema -// "github_api : GitHub" as github : coletarMetricasGitHub(inicio, fim)
activate github

sonarQube -> sonarQube : b:=processarMetricas(inicio, fim)
activate sonarQube

deactivate sonarQube
sonarQube ->": banco de dados" as bd : [fim < metricaAtual=true] persistirMetricas(metricas)


github -> github : c:=processarMetricas(inicio, fim)
activate github

deactivate github
github -> bd : [fim < metricaAtual=true] persistirMetricas(metricas)


bd --> usuario : retornarMensagemDeSuceso()

' sonarQube --> sistema : [fim < metricaAtual=true]retornarMetricasSonarQube(dadosSonarQube)

' deactivate github
' github --> sistema : [fim < metricaAtual=true]retornarMetricasGitHub(dadosGitHub)
' deactivate github
' sistema --> usuario: retornarTodasMetricas(dadosSonarQube, dadosGitHub)
deactivate sonarQube
deactivate github
deactivate sistema
deactivate usuario
@enduml
