## Diagrama de Caso de Uso

plantuml
@startuml
' ESCOLHER PROJETO



    "usuario : Usuario" as usuario -> ": barra de pesquisa" as pesquisa : pesquisaProjetos(nomeProjeto)
    activate usuario

    pesquisa -> ": banco de dados" as bd: e:=existe? \nconsultarBanco(nomeProjeto)
    activate pesquisa
    activate bd


    bd -> bd: e:=existe? \nbuscarProjeto(nomeProjeto)
    activate bd

    bd --> usuario: e:="sim" \nconsultarBanco()
    deactivate bd
    deactivate pesquisa
    deactivate usuario


      
@enduml