## Diagrama de Caso de Uso

plantuml
@startuml
mainframe ESCOLHER PROJETO

    "usuario : Usuario" as usuario -> "projeto : Projeto" as projeto : pesquisaProjetos(nomeProjeto)
    activate usuario

    activate projeto
    projeto -> ": banco de dados" as bd: e:=existe? \nconsultarBanco(nomeProjeto)
    activate bd



    bd -> bd: e:=existe? \nbuscarProjeto(nomeProjeto)
    activate bd


    deactivate bd
    bd --> usuario: e:="sim" \nconsultarBanco()
    deactivate bd
    deactivate projeto
    deactivate usuario


      
@enduml