@startuml
mainframe CONSULTAR ATIVIDADES NO PERÍODO ATUAL


"Usuario : usuario" as usuario -> "Atividade : atividade" as atividade : solicitarConsultaAtividades(data)
activate usuario
activate atividade

atividade --> ": banco de dados" as bd : obterAtividadesPeriodoAtual()
activate bd

bd -> bd : buscarAtividades()
activate bd

deactivate bd
bd --> atividade : retornarAtividades(dadosAtividades)
deactivate bd


atividade --> usuario : exibirAtividades(dadosAtividades)
deactivate atividade
deactivate usuario
@enduml