@startuml
mainframe GERAR RELATÓRIOS


"usuario : Usuario" as usuario -> "Relatorio : relatorio" as relatorio : solicitarGeracaoRelatorio(tipoRelatorio)
activate usuario

activate relatorio
relatorio -> ": banco de dados" as bd: coletarDadosRelatorio(tipoRelatorio)
activate bd

bd -> bd: buscarDados(tipoRelatorio)
activate bd

bd --> relatorio: [dadosEncontrados = "sim"] retornarDados(dadosRelatorio)
deactivate bd

relatorio -> relatorio: processarDados()
activate relatorio

deactivate relatorio

relatorio -> relatorio: formatarRelatorio()
activate relatorio

deactivate relatorio

relatorio --> usuario: exibirRelatorio(relatorio)
deactivate relatorio

deactivate usuario

@enduml