@startuml
' CONSULTAR MÉTRICAS DO GITHUB

"usuario : Usuario" as usuario -> "metrica : Metrica" as metrica : solicitarColeta()
activate usuario
activate metrica


metrica -> ": banco de dados" as bd : obterMetricas()
activate bd

bd -> bd : verificarDisponibilidade()
activate bd

deactivate bd
bd --> metrica : [disponivel = "sim"] retornarMetricas(dadosMetricas)
deactivate bd

metrica -> metrica : processarMetricas(dadosMetricas)
activate metrica

deactivate metrica
metrica --> usuario : exibirMetricas(dadosMetricas)
deactivate metrica

deactivate usuario

@enduml